/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/


import {Clone, useGLTF} from "@react-three/drei"
import {useControls} from "leva";

export default function Fibre() {
    const {v1, v2} = useControls('Versions du coffre',{
        v1:false,
        v2:false
    })
    const coffre1 = useGLTF("./Fibre/coffre_v1.gltf")
    const coffre2 = useGLTF("./Fibre/coffre_v2.gltf")
    const fibre = useGLTF("./Fibre/Fibre.glb")

    return <>
        <Clone object={fibre.scene} scale={6} rotation={[0, Math.PI/2, 0]}  />
        <Clone object={coffre1.scene} scale={6} rotation={[-Math.PI/2, 0, Math.PI/2]} visible={v1}  />
        <Clone object={coffre2.scene} scale={6} rotation={[-Math.PI/2, 0, Math.PI/2]} visible={v2} />
    </>


}

useGLTF.preload("./Fibre/Fibre.glb");
