/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/


import {Clone, Text, useGLTF} from "@react-three/drei"
import {useControls} from "leva";

export default function Fibre() {
    const {v1, v2, texte} = useControls('Versions du coffre',{
        v1:false,
        v2:false,
        texte:true
    })
    const coffre1 = useGLTF("./Fibre/coffre_v1.gltf")
    const coffre2 = useGLTF("./Fibre/coffre_v2.gltf")
    const fibre = useGLTF("./Fibre/Fibre.glb")

    return <>
        <Clone object={fibre.scene} scale={6} rotation={[0, Math.PI/2, 0]}  />
        <Clone object={coffre1.scene} scale={6} rotation={[-Math.PI/2, 0, Math.PI/2]} visible={v1}  />
        <Clone object={coffre2.scene} scale={6} rotation={[-Math.PI/2, 0, Math.PI/2]} visible={v2} />
        <Text visible={v1 && texte} color={"blue"} position={[ -0.4 , 1.2, -2]}  >
            V1
        </Text>
        <Text visible={v2 && texte} color={"brown"} position={[ -0.40 , 0, -2]} >
            V2
        </Text>
    </>


}

useGLTF.preload("./Fibre/Fibre.glb");
